<a href="https://colab.research.google.com/github/mahinkhan1408/NID-Data-extraction-project/blob/main/(1)_data_manipulation_and_agression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_train.csv')
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
af = pd.read_csv('/content/UCL_AllTime_Performance_Table - UCL_Alltime_Performance_Table.csv')
print(af)

         #               Team   M.    W   D    L       goals  Dif  Pt.
0      1.0        Real Madrid  486  291  85  110  1076:55:00  533  533
1      2.0     Bayern München  388  231  78   79   817:24:00  427  427
2      3.0       FC Barcelona  341  196  77   68   675:51:00  319  319
3      4.0  Manchester United  289  153  69   67   524:56:00  224  224
4      5.0           Juventus  297  151  68   78   472:57:00  171  171
..     ...                ...  ...  ...  ..  ...         ...  ...  ...
349  350.0       KR Reykjavík    6    0   0    6        7:35  -28  -28
350  351.0        Keflavík ÍF    8    0   0    8        5:35  -30  -30
351  352.0    Stade Dudelange    4    0   0    4        1:32  -31  -31
352  353.0   Union Luxembourg    8    0   0    8        2:39  -37  -37
353  354.0      Avenir Beggen    8    0   0    8        0:44  -44  -44

[354 rows x 9 columns]

In [ ]:
af.aggregate(['sum', 'min'])

,#,Team,M.,W,D,L,goals,Dif,Pt.
sum,56866.0,Real MadridBayern MünchenFC BarcelonaMancheste...,11772,4616,2538,4616,1076:55:00817:24:00675:51:00524:56:00472:57:00...,0,0
min,1.0,1. FC Frankfurt (Oder),2,0,0,0,0:1,-97,-97

In [ ]:
re = pd.read_csv('/content/RealEstateUnitedStates.csv')
print(re)

      Year     Month         Region Home Size  Average Sales Price  \
0     2022  December        Midwest    Double             144300.0
1     2022  December        Midwest   Single               82300.0
2     2022  December        Midwest    Total1             104700.0
3     2022  December      Northeast    Double             158300.0
4     2022  December      Northeast   Single               75300.0
...    ...       ...            ...       ...                  ...
1570  2014   January  United States   Single               48000.0
1571  2014   January  United States    Total1              68300.0
1572  2014   January           West    Double              93900.0
1573  2014   January           West   Single               55400.0
1574  2014   January           West    Total1              87700.0

      Number of Households (Thousands)  Median Income - Current Dollars  \
0                              28280.0                          73070.0
1                              28280.0                          73070.0
2                              28280.0                          73070.0
3                              22630.0                          80360.0
4                              22630.0                          80360.0
...                                ...                              ...
1570                          124600.0                          53660.0
1571                          124600.0                          53660.0
1572                           27910.0                          57690.0
1573                           27910.0                          57690.0
1574                           27910.0                          57690.0

      Median Income - 2022 Dollars  Mean Income - Current Dollars  \
0                          73070.0                       102400.0
1                          73070.0                       102400.0
2                          73070.0                       102400.0
3                          80360.0                       115300.0
4                          80360.0                       115300.0
...                            ...                            ...
1570                       64900.0                        75740.0
1571                       64900.0                        75740.0
1572                       69780.0                        79610.0
1573                       69780.0                        79610.0
1574                       69780.0                        79610.0

      Mean Income - 2022 Dollars
0                       102400.0
1                       102400.0
2                       102400.0
3                       115300.0
4                       115300.0
...                          ...
1570                     91610.0
1571                     91610.0
1572                     96300.0
1573                     96300.0
1574                     96300.0

[1575 rows x 10 columns]

In [ ]:
#lets find out the avergae sales price in united states region

avgprice= re.groupby('Region')['Average Sales Price'].mean()

print(avgprice)


avghome= re.groupby('Home Size')['Average Sales Price'].mean()
print(avghome)

Region
Midwest          77933.333333
Northeast        83359.365079
South            80594.603175
United States    82175.873016
West             93298.412698
Name: Average Sales Price, dtype: float64
Home Size
Double     107073.904762
Single      57197.523810
Total1      86145.523810
Name: Average Sales Price, dtype: float64

In [ ]:
goalavg = af.groupby('Team')['M.'].mean()
print(goalavg.to_string())

Team
1. FC Frankfurt (Oder)             21.0
1. FC Kaiserslautern               12.0
1. FC Köln                         17.0
1. FC Magdeburg                     8.0
1. FC Nürnberg                      8.0
1. FC Saarbrücken                   2.0
1. FC Union Berlin                  6.0
1899 Hoffenheim                     6.0
AB Gladsaxe                         4.0
AC Milan                          265.0
AC Sparta Praha                   102.0
ACF Fiorentina                     39.0
AE Lárissa                          2.0
AEK Athen                          56.0
AEL Limassol                        2.0
AFC Ajax                          215.0
AFC DWS                             6.0
AIK Solna                           8.0
AJ Auxerre                         20.0
APOEL Nikosia                      40.0
AS Monaco                          98.0
AS Roma                           109.0
AS Saint-Étienne                   39.0
AZ Alkmaar                         10.0
Aalborg BK                         12.0
Aarhus GF                          18.0
Aberdeen FC                        12.0
Anorthosis Famagusta                8.0
Apollon Limassol                    4.0
Ards FC                             2.0
Argeș Pitești                       8.0
Aris Bonnevoie                      6.0
Arsenal FC                        197.0
Aston Villa                        15.0
Atalanta                           23.0
Athletic Bilbao                    24.0
Athlone Town                        4.0
Atlético Madrid                   166.0
Austria Wien                       63.0
Avenir Beggen                       8.0
B 1903 København                    8.0
B 1909 Odense                       6.0
B 1913 Odense                       4.0
BATE Borisov                       30.0
BFC Dynamo                         36.0
BSC Young Boys                     35.0
Baník Ostrava                      14.0
Bayer Leverkusen                  107.0
Bayern München                    388.0
Beitar Jerusalem                    2.0
Beşiktaş                           70.0
Blackburn Rovers                    6.0
Boavista                           18.0
Bohemian FC                         6.0
Bohemians Praha 1905                4.0
Bologna FC                          3.0
Bor. Mönchengladbach               51.0
Borussia Dortmund                 176.0
Botev Plovdiv                       4.0
Brøndby IF                         20.0
Budapest Honvéd                    26.0
Budapesti Vasas                    27.0
Burnley FC                          4.0
Bursaspor                           6.0
CFR Cluj                           18.0
CSKA Moskva                        86.0
CSKA Sofia                         86.0
Cagliari Calcio                     4.0
Celtic FC                         156.0
Chelsea FC                        197.0
Chemnitzer FC                       2.0
Club Brugge KV                     97.0
Coleraine FC                        2.0
Cork Celtic                         2.0
Cork City                           2.0
Cork Hibernians                     2.0
Crusaders FC                        4.0
Crvena Zvezda                     104.0
Csepel SC                           2.0
Debreceni VSC                       6.0
Deportivo La Coruña                58.0
Derby County                       12.0
Derry City                          6.0
Dinamo Bucureşti                   54.0
Dinamo Kiev                       186.0
Dinamo Minsk                        8.0
Dinamo Tbilisi                      4.0
Dinamo Zagreb                      54.0
Djurgårdens IF                      8.0
Dnipro Dnipropetrovsk              12.0
Drumcondra Dublin                   6.0
Dundalk FC                         16.0
Dundee FC                           8.0
Dundee United                       8.0
Dynamo Dresden                     30.0
EPA Larnaca                         2.0
Eintracht Braunschweig              5.0
Eintracht Frankfurt                15.0
Erzgebirge Aue                     16.0
Esbjerg fB                         12.0
Etar Veliko Tarnovo                 2.0
Everton FC                          8.0
FC Aarau                            2.0
FC Admira Wacker                    2.0
FC Ararat                           6.0
FC Barcelona                      341.0
FC Basel                           82.0
FC Blau Weiß Linz                   2.0
FC Carl Zeiss Jena                  8.0
FC Differdange 03                   2.0
FC Dinamo City                      6.0
FC Hradec Králové                   4.0
FC Kuusysi (old)                   14.0
FC København                       44.0
FC La Chaux-de-Fonds                4.0
FC Lausanne-Sport                   2.0
FC Luzern                           2.0
FC Midtjylland                      6.0
FC Nantes                          40.0
FC Nordsjælland                     6.0
FC Petržalka                        6.0
FC Porto                          265.0
FC Reipas Lahti (old)               8.0
FC Schalke 04                      73.0
FC Sheriff                          6.0
FC Sion                             4.0
FC Thun Berner Oberland             6.0
FC Twente                           6.0
FC Unirea                           6.0
FC Universitatea Craiova           12.0
FC Utrecht                          2.0
FC VSS Košice                       6.0
FC Wacker Innsbruck                22.0
FC Zürich                          33.0
FCSB                               87.0
FK Astana                           6.0
FK Krasnodar                        6.0
FK Partizani                       14.0
FK Rostov                           6.0
FK Sarajevo                         6.0
FK Viagem Příbram                  45.0
FK Vllaznia                         2.0
FK Žalgiris                         2.0
FKS Stal Mielec                     4.0
Fenerbahçe                         73.0
Ferencvárosi TC                    32.0
Feyenoord                          85.0
Flamurtari Vlorë                    2.0
Floriana FC                        14.0
Fram Reykjavík                      8.0
Fredrikstad FK                      8.0
Galatasaray                       161.0
Girondins Bordeaux                 50.0
Glenavon FC                         2.0
Glentoran FC                       20.0
Grasshopper Club Zürich            38.0
Gwardia Warszawa                    5.0
Győri ETO FC                       14.0
Górnik Zabrze                      43.0
HJK Helsinki                       28.0
HPS Helsinki                        2.0
Hajduk Split                       26.0
Haka Valkeakoski                    8.0
Halmstads BK                        4.0
Hamburger SV                       39.0
Hamrun Spartans                     8.0
Hansa Rostock                       2.0
Hapoel Tel Aviv                     6.0
Heart of Midlothian                 4.0
Hellas Verona                       4.0
Helsingborgs IF                     6.0
Helsingfors IFK                     4.0
Hertha BSC                         12.0
Hibernian FC                        6.0
Hibernians FC                      12.0
Hvidovre IF                         8.0
IFK Göteborg                       70.0
IFK Malmö                           6.0
IFK Norrköping                     12.0
IK Start                            4.0
Ilves Tampere                       2.0
Inter                             203.0
Inter Bratislava                    4.0
Ipswich Town                        4.0
Jeunesse Esch                      39.0
Juventus                          297.0
KA Akureyri                         2.0
KAA Gent                            8.0
KB København                       11.0
KF Elbasani                         2.0
KF Tiranë                          16.0
KPV Kokkola                         2.0
KR Reykjavík                        6.0
KRC Genk                           18.0
KSK Beveren                         6.0
KV Mechelen                         6.0
Keflavík ÍF                         8.0
Kilmarnock FC                       4.0
Kuopion PS                          6.0
Køge BK                             2.0
LASK                                2.0
Lazio Roma                         60.0
Lech Poznań                        16.0
Leeds United                       38.0
Legia Warszawa                     32.0
Leicester City                     10.0
Levski Sofia                       28.0
Lierse SK                           8.0
Lille OSC                          46.0
Lillestrøm SK                      12.0
Limerick FC (old)                   4.0
Linfield FC                        40.0
Lisburn Distillery                  2.0
Liverpool FC                      230.0
Lokomotiv Moskva                   44.0
Lokomotiv Sofia                     8.0
Lyn Oslo                           10.0
Lyngby BK                           6.0
MFK Vítkovice                       4.0
MTK Budapest                       10.0
Maccabi Haifa                      18.0
Maccabi Tel Aviv                   14.0
Malmö FF                           53.0
Manchester City                   127.0
Manchester United                 289.0
Molde FK                            6.0
Montpellier HSC                     6.0
Moss FK                             2.0
Málaga CF                          10.0
MŠK Žilina                          6.0
NK Maribor                         18.0
Neuchâtel Xamax FCS                 8.0
Newcastle United                   24.0
Nottingham Forest                  20.0
OGC Nice                           14.0
OPS Oulu                            4.0
Odense BK                           6.0
Olimpija Ljubljana                  2.0
Olympiakos Nikosia                  6.0
Olympiakos Piraeus                156.0
Olympique Lyon                    136.0
Olympique Marseille               110.0
Omonia Nikosia                     36.0
Oţelul Galaţi                       6.0
PAOK Saloniki                       6.0
PFC Beroe                           2.0
PFC Ludogorets Razgrad             12.0
PSV Eindhoven                     171.0
Panathinaikos                     127.0
Paris Saint-Germain               151.0
Parma Calcio 1913                   6.0
Partizan                           45.0
Petrolul Ploieşti                   8.0
Pezoporikos Larnaca                 2.0
Polonia Bytom                       6.0
Portadown FC                        4.0
Progrès Niedercorn                  4.0
Qarabağ FK                          6.0
RB Leipzig                         46.0
RB Salzburg                        38.0
RC Celta                            8.0
RC Lens                            18.0
RC Strasbourg                       6.0
RCD Mallorca                        6.0
RSC Anderlecht                    163.0
RWDM Brussels FC                    4.0
Rabat Ajax                          4.0
Rangers FC                        131.0
Rapid Bucureşti                     4.0
Rapid Wien                         61.0
Real Betis                          6.0
Real Madrid                       486.0
Real Sociedad                      32.0
Roda JC Kerkrade                    2.0
Rosenborg BK                       90.0
Rot-Weiss Essen                     2.0
Royal Antwerp FC                    8.0
Rubin Kazan                        12.0
Ruch Chorzów                       14.0
SG Sachsen Leipzig                  2.0
SL Benfica                        266.0
SSC Napoli                         66.0
Sampdoria                          11.0
Servette FC                        17.0
Sevilla FC                         72.0
Shakhtar Donetsk                  118.0
Shamrock Rovers                    14.0
Shelbourne FC                       2.0
Skeid Fotball                       2.0
Skonto FC                           4.0
Slavia Praha                       12.0
Sliema Wanderers                   14.0
Sligo Rovers                        2.0
Slovan Bratislava                  16.0
Sparta Rotterdam                    6.0
Spartak Moskva                    104.0
Spartak Plovdiv                     4.0
Spartak Trnava                     24.0
Spora Luxemburg                     7.0
Sporting Braga                     18.0
Sporting CP                        92.0
St Patrick's Athletic               2.0
Stade Dudelange                     4.0
Stade Reims                        24.0
Stade Rennais                       6.0
Standard Liège                     46.0
Strømsgodset IF                     2.0
Sturm Graz                         24.0
Szombierki Bytom                    4.0
TPS Turku                           8.0
TSV 1860 München                    4.0
Tavriya Simferopol (1958-2014)      2.0
Torino FC                           4.0
Torpedo Moskva                      4.0
Tottenham Hotspur                  61.0
Trabzonspor                        20.0
UTA Arad                            6.0
Udinese Calcio                      6.0
Union Luxembourg                    8.0
Valencia CF                       116.0
Valletta FC                        10.0
Valur Reykjavík                    16.0
Vardar Skopje                       2.0
Vejle BK                           12.0
VfB Stuttgart                      27.0
VfL Wolfsburg                      22.0
Viking FK                          14.0
Viktoria Plzeň                     24.0
Villarreal CF                      40.0
Vojvodina                           9.0
Vålerenga IF                        6.0
Víkingur Reykjavík                  6.0
Waterford FC                       12.0
Werder Bremen                      60.0
Widzew Łódź                        16.0
Wiener Sport-Club                  12.0
Willem II                           6.0
Wisła Kraków                        6.0
Wolverhampton Wanderers             8.0
Zagłębie Lubin                      2.0
Zbrojovka Brno                      4.0
Zenit St. Petersburg               64.0
Zorya Lugansk                       4.0
sc Heerenveen                       6.0
Åtvidabergs FF                      8.0
ÍA Akranes                         16.0
ÍBV Vestmannaeyjar                  2.0
Örgryte IS                          2.0
Östers IF                           8.0
Újpest FC                          40.0
İstanbul Başakşehir                 6.0
ŁKS Łódź                            2.0
Śląsk Wrocław                       2.0
Željezničar Sarajevo                2.0

In [ ]:
esus = pd.read_csv('/content/excel_export (1).csv')

print(esus)

        Status                WO #      Work Type  Client State  Date Due  \
0    Cancelled          1061203253   Snow Removal    9102    IL  02-06-25
1    Cancelled          1061201299   Snow Removal    9102    IL  01-31-25
2    Cancelled          1061199149   Snow Removal    9102    IL  01-22-25
3    Cancelled          1061197921   Snow Removal    9102    WI  01-17-25
4       Closed          1061196387   Snow Removal    9102    IL  01-11-25
..         ...                 ...            ...     ...   ...       ...
495     Closed  101992- Electrical  Turn Estimate    2115    IN  05-15-24
496     Closed      101992- Stairs  Turn Estimate    2115    IN  05-15-24
497     Closed         00579946-BA    OM Approval    9111    AL  05-15-24
498  Cancelled              215017    OM Estimate    6609    PA  05-15-24
499     Closed     453149587-IS-Z1      Misc.Work    9106    MS  05-15-24

    Ready Office Date Received         Category Customer        Loan #  \
0            NaN      02-06-24  Ready To Assign      271    ######2682
1            NaN      01-31-24  Ready To Assign      271    ######3462
2       04-01-24      01-22-24  Ready To Assign      251    ######7315
3       04-01-24      03-19-24  Ready To Assign      271    ######9863
4       01-22-24      01-11-24  Ready To Assign      251    ######7315
..           ...           ...              ...      ...           ...
495     05-16-24      05-13-24             RUSH      NaN           NaN
496     05-14-24      05-13-24             RUSH      NaN           NaN
497     05-24-24      05-13-24             RUSH      NaN           NaN
498          NaN      05-13-24              NaN      NaN           NaN
499     05-21-24      05-13-24  Ready To Assign      NaN  0680668209-0

                Address             City    Zip          Contractor  \
0     8421 S Paulina St          Chicago  60620       Emmanuel Sosa
1      1224  Landon Ave  Winthrop Harbor  60096       Emmanuel Sosa
2       409  Prairie St         Kirkland  60146  Brandi Covarrubias
3     506 S Indiana Ave        West Bend  53095             Jacob R
4       409  Prairie St         Kirkland  60146  Brandi Covarrubias
..                  ...              ...    ...                 ...
495   4688 Briarwood Dr         Newburgh  47630         Theo Tafhim
496   4688 Briarwood Dr         Newburgh  47630         Theo Tafhim
497  1723 6th Pl Cir NW     Center Point  35215            Samuel H
498  1508 Brookstone Pl       Hellertown  18055            Amilia T
499    110 MAGNOLIA CIR          JACKSON  39209      Sylvia Preston

           Admin  Photos
0            NaN       0
1            NaN       0
2            NaN       0
3            NaN       0
4            NaN      28
..           ...     ...
495  Theo Tafhim       2
496  Theo Tafhim       3
497          NaN      14
498      Sunny A       1
499          NaN      62

[500 rows x 17 columns]

**Aggregate**

* aggregation dataset
* sum,max,min

In [ ]:
esus.aggregate(['sum', 'min'])

KeyError: "Column(s) ['Column1', 'Column2'] do not exist"